### ISSUE TITLE
change server name 

### ISSUE THREAD

**Issue by Ley-VN** [meower1/v2meow#2]
i want to change www.samsung.com to dl.kgvn.garenanow
But not working

**Comment by meower1** [comment]
hey there, yes there currently isn't an option to manually change the sni/dest from the script side but ill consider adding it.
for now u can follow these steps to do so:
1 - nano /usr/local/etc/xray/config.json
2- change the "dest" to "dl.kgvn.garenanow:443" and 
3- change the "serverNames" parameter to "dl.kgvn.garenanow"
4- ctrl + s and ctrl + x
5- systemctl restart xray

and u should be set to go. have a good day :)

**Comment by Ley-VN** [comment]
please help me one last time
I'm so stupid
I want to add dns server to block ads
Use dns doh
Example: https://dns google
Can you guide me to configure the server?
Please help me, because I'm stupid
Configure xray server

**Comment by meower1** [comment]
in order to set a custom dns for ur config u must change the dns parameter in the xray config. heres the official xray documentation for it : https://xtls.github.io/config/dns.html#dnsobject

so run this : nano /usr/local/etc/xray/config.json
then change ur dns based on the documentation.

feel free to ask any questions u have ill answer if i can 🙂

**Comment by meower1** [comment]
i updated the script and now theres a "4. manual mode" option where u can set ur prefered sni. thanks for the suggestion 🌷 🙂

**Comment by Ley-VN** [comment]
Thank you
Now I want to remove sniffing 
It blocks the app connection that I use.
Instructions on how to delete it

**Comment by Ley-VN** [comment]
> to set dns tùy chỉnh cho cấu hình của bạn, bạn phải thay đổi tham số dns trong cấu hình xray. đây là tài liệu xray chính thức cho nó: https://xtls.github.io/config/dns.html#dnsobject
> 
> vì vậy hãy chạy cái này: nano /usr/local/etc/xray/config.json sau đó thay đổi dns của bạn dựa trên tài liệu.
> 
> cứ thoải mái hỏi bất kỳ câu hỏi nào nếu tôi có thể🙂

I followed the instructions, but it didn't work.
1I use doh nextdns.io
